apiVersion: v1
kind: Service
metadata:
  name: helloapp
  namespace: helloapp
  labels:
    app: helloapp
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: helloapp